export const SIGN_IN = 'SIGN_IN'
export const SIGN_UP = 'SIGN_UP'
export const SIGN_OUT = 'SIGN_OUT'
export const RESOURCE_DATA = 'RESOURCE_DATA'
export const UPDATE_USER = 'UPDATE_USER'
export const RESOURCE_SINGLE_DATA = 'RESOURCE_SINGLE_DATA'
